name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  
      - name: install packages
        run: make install
      - name: List installed packages
        run: pip list
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: generate_and_push
        run: make generate_and_push
      - name: format
        run: make format
      #- name: Test Jupyter Notebook with nbval
       # run: |
         # pip install pytest nbval
          #pytest --nbval individual_project_1.ipynb
